# Generated by Django 4.1.7 on 2023-05-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_alt_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude',
        ),
    ]
