# Generated by Django 4.1.7 on 2023-03-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('tag', models.CharField(max_length=100, null=True)),
                ('duration', models.FloatField()),
                ('overview', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_live_on_website', models.BooleanField(default=False)),
                ('start_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendored', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('live_on_website', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_vendor', to='superadmin.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_course', to='superadmin.course')),
                ('subtopic_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='superadmin.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsAndJobOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='superadmin.course')),
            ],
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('results_and_jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to='superadmin.resultsandjobopportunities')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_feature', to='superadmin.course')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField(max_length=200)),
                ('answer', models.TextField(max_length=300)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_faq', to='superadmin.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAndCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('certificate', models.ImageField(null=True, upload_to='images/')),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_exam', to='superadmin.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_training', to='superadmin.training'),
        ),
    ]
