# Generated by Django 4.1.7 on 2023-03-24 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_training_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_live_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
