# Generated by Django 4.1.7 on 2023-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
