# Generated by Django 4.1.7 on 2023-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_vendor_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
