# Generated by Django 4.1.7 on 2023-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_training_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
