# Generated by Django 4.1.7 on 2023-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_alter_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
