# Generated by Django 4.1.7 on 2023-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_alter_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
