# Generated by Django 4.1.7 on 2023-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_remove_course_price_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_live_on_website',
            field=models.CharField(max_length=10),
        ),
    ]
