# Generated by Django 4.1.7 on 2023-05-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_alter_course_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
