# Generated by Django 4.1.7 on 2023-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_remove_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
