# Generated by Django 4.1.7 on 2023-05-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_alter_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examandcertification',
            name='certificate',
        ),
    ]
