# Generated by Django 4.1.7 on 2023-05-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_remove_examandcertification_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='image',
        ),
    ]
