# Generated by Django 4.1.7 on 2023-06-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisites',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisite', to='superadmin.course'),
            preserve_default=False,
        ),
    ]
