# Generated by Django 4.1.7 on 2023-06-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_prerequisites_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prerequisites',
            new_name='Prerequisite',
        ),
    ]
