# Generated by Django 4.1.7 on 2023-03-24 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_rename_image_vendor_logo_vendor_created_at_and_more'),
        ('training', '0005_instructor_enrollment_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_enquiry', to='superadmin.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
