# Generated by Django 4.1.7 on 2023-03-29 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
