# Generated by Django 4.1.7 on 2023-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_contactus_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
