# Generated by Django 4.1.7 on 2023-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_emailsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='remark',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
