# Generated by Django 4.1.7 on 2023-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_instructor_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='remark',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
